version: "3.9"

services:
  jupyter:
    image: project-pytorch-image:latest
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: "project-pytorch-container"
    # restart: unless-stopped
    ports:
      - "8899:8888"
    environment:
      - "JUPYTER_ENABLE_LAB: yes"
      - "JUPYTER_TOKEN: docker"
    volumes:
      - ../project:/project
    command: bash -c "pip install -r /project/additional-requirements.txt && jupyter lab --ip=0.0.0.0 --allow-root"
    deploy:
      resources:
        limits:
          memory: 6G